### ISSUE TITLE
Cannot reproduce failure on `bevy_prototype_debug_lines`

### ISSUE THREAD

**Issue by jakobhellermann** [saethlin/miri-tools#16]
I wanted to reproduce <https://asan.saethlin.dev/ub?crate=bevy_prototype_debug_lines&version=0.8.1> locally so created a file containing `bevy_prototype_debug_lines` and ran `cargo run -- --crate-list that_file` but all I got was
```
[2022-11-02T12:16:37Z INFO  miri_the_world::db_dump] Downloading crate database
[2022-11-02T12:17:04Z INFO  miri_the_world::db_dump] Processing crate database
[2022-11-02T12:17:09Z INFO  miri_the_world] Building list of crates to run
Running bevy_prototype_debug_lines 0.8.1
Finished bevy_prototype_debug_lines 0.8.1
2022-11-02T12:17:09Z INFO  miri_the_world] done!
```
I am on the `asan` branch and `cargo 1.67.0-nightly (7e484fc1a 2022-10-27)`.
I didn't see any build logs, and after processing the database the output was done very quickly.
Any idea what might have gone wrong?

**Comment by saethlin** [comment]
> I didn't see any build logs

Nothing appeared in `logs/`? At a guess, did you build the docker image this requires first? (The Rust program should really do this for you...)

The build logs end with a copy of the `Cargo.lock` that the build used. It looks from the backtrace like this issue is actually in `bevy_ecs`. Is there a newer version of `bevy_ecs` that fixes this issue?
